In [1]:
import numpy as np

## 1.clean the data(outlier,missing values,type conversion)
### sepal width

In [4]:
Iris = np.genfromtxt(r"C:\Users\subha\Downloads\Iris_clean_-_Copy.csv",dtype = 'int32', delimiter = ',')
Iris

array([[ -1,  -1,  -1,  -1],
       [  5,   3,   1,   0],
       [  4,   3,   1,   0],
       [  4,   3,   1,   0],
       [  4,   3,   1,  10],
       [ 50,   3,   1,   0],
       [  5,  -1,   1,   0],
       [  4,   3,   1,   0],
       [  5,   3,   1,   0],
       [  4,   2,   1,   0],
       [  4,   3,  -1,   0],
       [  5,   3,   1,   0],
       [  4,   3,   1,   0],
       [  4, 130,   1,  10],
       [  4,   3,   1,   0],
       [  5,   4,   1,   0],
       [  5,   4,   1,   0],
       [ 50,  -1,   1,   0],
       [  5,   3,   1,   0],
       [  5,   3,   1,   0],
       [  5,   3,   1,   0],
       [  5,   3,   1,   0],
       [  5,   3,   1,   0],
       [  4,   3,   1,   0],
       [  5,   3,   1,   0],
       [  4,   3,   1,   0],
       [  5,   3,   1,   0],
       [  5,  34,   1,   0],
       [  5,   3,   1,   0],
       [  5,   3,   1, 110],
       [  4,   3,   1,   0],
       [  4,   3,   1,   0],
       [  5,   3,   1,   0],
       [  5,   4,   1,   0],
       [  5,  

In [5]:
width = Iris[1:,1]
width

array([  3,   3,   3,   3,   3,  -1,   3,   3,   2,   3,   3,   3, 130,
         3,   4,   4,  -1,   3,   3,   3,   3,   3,   3,   3,   3,   3,
        34,   3,   3,   3,   3,   3,   4,   4,   3,   3,   3,   3,   3,
         3,   3,   2,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
        -1,   2,   2,   2,   3,   2,   2,   2,   2,   3,   2,   2,   2,
         3,   3,   2,   2,   2,   3,   2,   2,  -1,   2,   3,   2,   3,
         2,   2,   2,   2,   2,   2,   3,   3,   3,   2,   3,   2,   2,
         3, 112,   2,   2,   3,   2,   2,   2,   2,   3,   2,   3,   2,
         3,   3,   2,   2,   2,   3,   3,   2,   3,   2,   2,   3,   3,
         3,   2,   2,   3,   2,   2,   2,   3,   3,   2,   3,   2,   3,
         2,   3,   2,   2,   2,   3,   3,  -1,   3,   3,   3,   3,   2,
         3,   3,  -1,   2,   3,   3,   3,   2,   2,   2,   3,   3,   2,
         2,   2,   3,   2,   2,   2,   3,   3,   2])

In [6]:
Iris = np.where(width == -1,np.nan,width) #nan values
Iris

array([  3.,   3.,   3.,   3.,   3.,  nan,   3.,   3.,   2.,   3.,   3.,
         3., 130.,   3.,   4.,   4.,  nan,   3.,   3.,   3.,   3.,   3.,
         3.,   3.,   3.,   3.,  34.,   3.,   3.,   3.,   3.,   3.,   4.,
         4.,   3.,   3.,   3.,   3.,   3.,   3.,   3.,   2.,   3.,   3.,
         3.,   3.,   3.,   3.,   3.,   3.,   3.,   3.,  nan,   2.,   2.,
         2.,   3.,   2.,   2.,   2.,   2.,   3.,   2.,   2.,   2.,   3.,
         3.,   2.,   2.,   2.,   3.,   2.,   2.,  nan,   2.,   3.,   2.,
         3.,   2.,   2.,   2.,   2.,   2.,   2.,   3.,   3.,   3.,   2.,
         3.,   2.,   2.,   3., 112.,   2.,   2.,   3.,   2.,   2.,   2.,
         2.,   3.,   2.,   3.,   2.,   3.,   3.,   2.,   2.,   2.,   3.,
         3.,   2.,   3.,   2.,   2.,   3.,   3.,   3.,   2.,   2.,   3.,
         2.,   2.,   2.,   3.,   3.,   2.,   3.,   2.,   3.,   2.,   3.,
         2.,   2.,   2.,   3.,   3.,  nan,   3.,   3.,   3.,   3.,   2.,
         3.,   3.,  nan,   2.,   3.,   3.,   3.,   

In [7]:
np.nanmedian(width)

3.0

In [8]:
Iris = np.where(np.isnan(width),np.nanmedian(width),width)
Iris

array([  3.,   3.,   3.,   3.,   3.,  -1.,   3.,   3.,   2.,   3.,   3.,
         3., 130.,   3.,   4.,   4.,  -1.,   3.,   3.,   3.,   3.,   3.,
         3.,   3.,   3.,   3.,  34.,   3.,   3.,   3.,   3.,   3.,   4.,
         4.,   3.,   3.,   3.,   3.,   3.,   3.,   3.,   2.,   3.,   3.,
         3.,   3.,   3.,   3.,   3.,   3.,   3.,   3.,  -1.,   2.,   2.,
         2.,   3.,   2.,   2.,   2.,   2.,   3.,   2.,   2.,   2.,   3.,
         3.,   2.,   2.,   2.,   3.,   2.,   2.,  -1.,   2.,   3.,   2.,
         3.,   2.,   2.,   2.,   2.,   2.,   2.,   3.,   3.,   3.,   2.,
         3.,   2.,   2.,   3., 112.,   2.,   2.,   3.,   2.,   2.,   2.,
         2.,   3.,   2.,   3.,   2.,   3.,   3.,   2.,   2.,   2.,   3.,
         3.,   2.,   3.,   2.,   2.,   3.,   3.,   3.,   2.,   2.,   3.,
         2.,   2.,   2.,   3.,   3.,   2.,   3.,   2.,   3.,   2.,   3.,
         2.,   2.,   2.,   3.,   3.,  -1.,   3.,   3.,   3.,   3.,   2.,
         3.,   3.,  -1.,   2.,   3.,   3.,   3.,   

In [9]:
con = (Iris > 5) | (Iris < 2) # outlier


In [10]:
sepal_width = np.where(con,3,Iris)
sepal_width

array([3., 3., 3., 3., 3., 3., 3., 3., 2., 3., 3., 3., 3., 3., 4., 4., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 4.,
       3., 3., 3., 3., 3., 3., 3., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 2., 2., 2., 3., 2., 2., 2., 2., 3., 2., 2., 2., 3., 3., 2.,
       2., 2., 3., 2., 2., 3., 2., 3., 2., 3., 2., 2., 2., 2., 2., 2., 3.,
       3., 3., 2., 3., 2., 2., 3., 3., 2., 2., 3., 2., 2., 2., 2., 3., 2.,
       3., 2., 3., 3., 2., 2., 2., 3., 3., 2., 3., 2., 2., 3., 3., 3., 2.,
       2., 3., 2., 2., 2., 3., 3., 2., 3., 2., 3., 2., 3., 2., 2., 2., 3.,
       3., 3., 3., 3., 3., 3., 2., 3., 3., 3., 2., 3., 3., 3., 2., 2., 2.,
       3., 3., 2., 2., 2., 3., 2., 2., 2., 3., 3., 2.])

In [11]:
sepal_width = np.array(sepal_width,dtype = "float16")
sepal_width

array([3., 3., 3., 3., 3., 3., 3., 3., 2., 3., 3., 3., 3., 3., 4., 4., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 4.,
       3., 3., 3., 3., 3., 3., 3., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 2., 2., 2., 3., 2., 2., 2., 2., 3., 2., 2., 2., 3., 3., 2.,
       2., 2., 3., 2., 2., 3., 2., 3., 2., 3., 2., 2., 2., 2., 2., 2., 3.,
       3., 3., 2., 3., 2., 2., 3., 3., 2., 2., 3., 2., 2., 2., 2., 3., 2.,
       3., 2., 3., 3., 2., 2., 2., 3., 3., 2., 3., 2., 2., 3., 3., 3., 2.,
       2., 3., 2., 2., 2., 3., 3., 2., 3., 2., 3., 2., 3., 2., 2., 2., 3.,
       3., 3., 3., 3., 3., 3., 2., 3., 3., 3., 2., 3., 3., 3., 2., 2., 2.,
       3., 3., 2., 2., 2., 3., 2., 2., 2., 3., 3., 2.], dtype=float16)

## sepal length


In [18]:
sepal_length = iris[1:,0]
sepal_length

array([  5,   4,   4,   4,  50,   5,   4,   5,   4,   4,   5,   4,   4,
         4,   5,   5,  50,   5,   5,   5,   5,   5,   4,   5,   4,   5,
         5,   5,   5,   4,   4,   5,   5,   5,   4,   5,   5,   4,   4,
         5,   5,   4,   4,   5,   5,   4,   5,   4,   5,   5,   7,   6,
         6,   5,   6,   5, 116,   4,   6,   5,   5,   5,   6,   6,   5,
         6,   5,   5,   6,   5,   5,   6,   6,   6,   6,   6,   6,   6,
         6,   5,   5,   5,   5,   6,   5,   6,   6,   6,   5,   5,   5,
         6,   5,   5,   5,   5,   5,   6,   5,   5,   6,   5,   7,   6,
         6,   7,   4,   7,   6,   7,   6,   6,   6,   5,   5,   6,   6,
         7,   7,   6,   6,   5,   7,   6,   6,   7,   6,   6,   6,  70,
        -1,  -1,   6,   6,   6,   7,   6,   6,   6,   6,   6,   6,   5,
         6,   6,   6,   6,   6,   6,   5,   5,   7,  -1,  -1,   7,   4,
         7,   6,   5,   5,   7,   6,   7,   6,   6])

In [19]:
np.nanmedian(sepal_length)

5.0

In [20]:
a = np.where(np.isnan(sepal_length),np.nanmedian(sepal_length),sepal_length)  # replace nan with nanmedian
a

array([  5.,   4.,   4.,   4.,  50.,   5.,   4.,   5.,   4.,   4.,   5.,
         4.,   4.,   4.,   5.,   5.,  50.,   5.,   5.,   5.,   5.,   5.,
         4.,   5.,   4.,   5.,   5.,   5.,   5.,   4.,   4.,   5.,   5.,
         5.,   4.,   5.,   5.,   4.,   4.,   5.,   5.,   4.,   4.,   5.,
         5.,   4.,   5.,   4.,   5.,   5.,   7.,   6.,   6.,   5.,   6.,
         5., 116.,   4.,   6.,   5.,   5.,   5.,   6.,   6.,   5.,   6.,
         5.,   5.,   6.,   5.,   5.,   6.,   6.,   6.,   6.,   6.,   6.,
         6.,   6.,   5.,   5.,   5.,   5.,   6.,   5.,   6.,   6.,   6.,
         5.,   5.,   5.,   6.,   5.,   5.,   5.,   5.,   5.,   6.,   5.,
         5.,   6.,   5.,   7.,   6.,   6.,   7.,   4.,   7.,   6.,   7.,
         6.,   6.,   6.,   5.,   5.,   6.,   6.,   7.,   7.,   6.,   6.,
         5.,   7.,   6.,   6.,   7.,   6.,   6.,   6.,  70.,  -1.,  -1.,
         6.,   6.,   6.,   7.,   6.,   6.,   6.,   6.,   6.,   6.,   5.,
         6.,   6.,   6.,   6.,   6.,   6.,   5.,   

In [21]:
con = a > 8  # outlier


In [22]:
sepal_length = np.where(con,5,a)
sepal_length

array([ 5.,  4.,  4.,  4.,  5.,  5.,  4.,  5.,  4.,  4.,  5.,  4.,  4.,
        4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  4.,  5.,  4.,  5.,
        5.,  5.,  5.,  4.,  4.,  5.,  5.,  5.,  4.,  5.,  5.,  4.,  4.,
        5.,  5.,  4.,  4.,  5.,  5.,  4.,  5.,  4.,  5.,  5.,  7.,  6.,
        6.,  5.,  6.,  5.,  5.,  4.,  6.,  5.,  5.,  5.,  6.,  6.,  5.,
        6.,  5.,  5.,  6.,  5.,  5.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  5.,  5.,  5.,  5.,  6.,  5.,  6.,  6.,  6.,  5.,  5.,  5.,
        6.,  5.,  5.,  5.,  5.,  5.,  6.,  5.,  5.,  6.,  5.,  7.,  6.,
        6.,  7.,  4.,  7.,  6.,  7.,  6.,  6.,  6.,  5.,  5.,  6.,  6.,
        7.,  7.,  6.,  6.,  5.,  7.,  6.,  6.,  7.,  6.,  6.,  6.,  5.,
       -1., -1.,  6.,  6.,  6.,  7.,  6.,  6.,  6.,  6.,  6.,  6.,  5.,
        6.,  6.,  6.,  6.,  6.,  6.,  5.,  5.,  7., -1., -1.,  7.,  4.,
        7.,  6.,  5.,  5.,  7.,  6.,  7.,  6.,  6.])

In [23]:
sepallength = np.array(sepal_length,dtype = "float16")
sepallength

array([ 5.,  4.,  4.,  4.,  5.,  5.,  4.,  5.,  4.,  4.,  5.,  4.,  4.,
        4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  4.,  5.,  4.,  5.,
        5.,  5.,  5.,  4.,  4.,  5.,  5.,  5.,  4.,  5.,  5.,  4.,  4.,
        5.,  5.,  4.,  4.,  5.,  5.,  4.,  5.,  4.,  5.,  5.,  7.,  6.,
        6.,  5.,  6.,  5.,  5.,  4.,  6.,  5.,  5.,  5.,  6.,  6.,  5.,
        6.,  5.,  5.,  6.,  5.,  5.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  5.,  5.,  5.,  5.,  6.,  5.,  6.,  6.,  6.,  5.,  5.,  5.,
        6.,  5.,  5.,  5.,  5.,  5.,  6.,  5.,  5.,  6.,  5.,  7.,  6.,
        6.,  7.,  4.,  7.,  6.,  7.,  6.,  6.,  6.,  5.,  5.,  6.,  6.,
        7.,  7.,  6.,  6.,  5.,  7.,  6.,  6.,  7.,  6.,  6.,  6.,  5.,
       -1., -1.,  6.,  6.,  6.,  7.,  6.,  6.,  6.,  6.,  6.,  6.,  5.,
        6.,  6.,  6.,  6.,  6.,  6.,  5.,  5.,  7., -1., -1.,  7.,  4.,
        7.,  6.,  5.,  5.,  7.,  6.,  7.,  6.,  6.], dtype=float16)

## petal length


In [26]:
petal_length = iris[1:,2]
petal_length

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 13,  1,  1,  1,  1,  1,  1,  1,  1,  4,
        4,  4,  4,  4,  4,  4,  3,  4,  3,  3,  4,  4,  4,  3,  4,  4,  4,
        4,  3,  4,  4,  4,  4,  4,  4,  4,  5,  4,  3, 13,  3,  3,  5,  4,
        4,  4,  4,  4,  4,  4, -1,  4,  3,  4,  4,  4,  4,  3,  4,  6,  5,
        5,  5,  5,  6,  4,  6,  5,  6,  5,  5, -1,  5,  5,  5,  5,  6,  6,
        5,  5,  4,  6,  4,  5,  6,  4,  4,  5,  5,  6, -1,  5,  5,  5,  6,
        5,  5,  4,  5, -1,  5,  5,  5,  5, -1,  5,  5,  5,  5,  4,  6,  4,
        5,  6,  4,  6,  5,  5,  4,  6,  4,  6,  5,  5])

In [27]:
np.nanmedian(petal_length)


4.0

In [28]:
a = np.where(np.isnan(petal_length),np.nanmedian(petal_length),petal_length) # replace missing value with nanmedian
a

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1., 13.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  3.,  4.,  3.,  3.,  4.,  4.,  4.,  3.,
        4.,  4.,  4.,  4.,  3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  5.,
        4.,  3., 13.,  3.,  3.,  5.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
       -1.,  4.,  3.,  4.,  4.,  4.,  4.,  3.,  4.,  6.,  5.,  5.,  5.,
        5.,  6.,  4.,  6.,  5.,  6.,  5.,  5., -1.,  5.,  5.,  5.,  5.,
        6.,  6.,  5.,  5.,  4.,  6.,  4.,  5.,  6.,  4.,  4.,  5.,  5.,
        6., -1.,  5.,  5.,  5.,  6.,  5.,  5.,  4.,  5., -1.,  5.,  5.,
        5.,  5., -1.,  5.,  5.,  5.,  5.,  4.,  6.,  4.,  5.,  6.,  4.,
        6.,  5.,  5.,  4.,  6.,  4.,  6.,  5.,  5.])

In [29]:
cond = (a < 1) | (a > 7)  # outlier


In [31]:
petal_length = np.where(cond,4,a)
petal_length

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 1., 1., 1., 1., 1., 1., 4.,
       4., 4., 4., 4., 4., 4., 3., 4., 3., 3., 4., 4., 4., 3., 4., 4., 4.,
       4., 3., 4., 4., 4., 4., 4., 4., 4., 5., 4., 3., 4., 3., 3., 5., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 3., 4., 4., 4., 4., 3., 4., 6., 5.,
       5., 5., 5., 6., 4., 6., 5., 6., 5., 5., 4., 5., 5., 5., 5., 6., 6.,
       5., 5., 4., 6., 4., 5., 6., 4., 4., 5., 5., 6., 4., 5., 5., 5., 6.,
       5., 5., 4., 5., 4., 5., 5., 5., 5., 4., 5., 5., 5., 5., 4., 6., 4.,
       5., 6., 4., 6., 5., 5., 4., 6., 4., 6., 5., 5.])

In [33]:
petalength = np.array(petal_length,dtype = "float16")
petallength

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 1., 1., 1., 1., 1., 1., 4.,
       4., 4., 4., 4., 4., 4., 3., 4., 3., 3., 4., 4., 4., 3., 4., 4., 4.,
       4., 3., 4., 4., 4., 4., 4., 4., 4., 5., 4., 3., 4., 3., 3., 5., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 3., 4., 4., 4., 4., 3., 4., 6., 5.,
       5., 5., 5., 6., 4., 6., 5., 6., 5., 5., 4., 5., 5., 5., 5., 6., 6.,
       5., 5., 4., 6., 4., 5., 6., 4., 4., 5., 5., 6., 4., 5., 5., 5., 6.,
       5., 5., 4., 5., 4., 5., 5., 5., 5., 4., 5., 5., 5., 5., 4., 6., 4.,
       5., 6., 4., 6., 5., 5., 4., 6., 4., 6., 5., 5.])

In [35]:
petal_width = iris[1:,3]
petal_width

array([  0,   0,   0,  10,   0,   0,   0,   0,   0,   0,   0,   0,  10,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0, 110,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   1,
         1,   1,   1,   1,   1,  16,   1,   1,   1,   1,   1,   1,   1,
         1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
         1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
         1,   1,   1,   1,   1,   1,   1, 111,   1,   2,   1,   2,   1,
         2,   2,   1,   1,   1,   2,   2,   1,   2,   2,   2,   2,   1,
         2,   2,   1,   2,   2,   2,   1,   2,   1,   1,   1,   2,   1,
         1,   2,   2,   1,   1,   2,   2,   1,   1,   2,   2,   2,   1,
         2,   2,   2,   1,   2,   2,   1,   2,   2,   1,   2,   1,   1,
         1,   1,   1,   2,   2,   1,   2,   2,   1])

In [36]:
np.nanmedian(petal_width)


1.0

In [37]:
a = np.where(np.isnan(petal_width),np.nanmedian(petal_width),petal_width) # replace missing value with nanmedian
a

array([  0.,   0.,   0.,  10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,  10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0., 110.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,  16.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1., 111.,
         1.,   2.,   1.,   2.,   1.,   2.,   2.,   1.,   1.,   1.,   2.,
         2.,   1.,   2.,   2.,   2.,   2.,   1.,   2.,   2.,   1.,   2.,
         2.,   2.,   1.,   2.,   1.,   1.,   1.,   2.,   1.,   1.,   2.,
         2.,   1.,   1.,   2.,   2.,   1.,   1.,   2.,   2.,   2.,   1.,
         2.,   2.,   2.,   1.,   2.,   2.,   1.,   

In [38]:
con = a > 11  # outlier


In [39]:
petalwidth = np.where(con,2,a)
petalwidth

array([ 0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  2.,  1.,  2.,  1.,
        2.,  2.,  1.,  1.,  1.,  2.,  2.,  1.,  2.,  2.,  2.,  2.,  1.,
        2.,  2.,  1.,  2.,  2.,  2.,  1.,  2.,  1.,  1.,  1.,  2.,  1.,
        1.,  2.,  2.,  1.,  1.,  2.,  2.,  1.,  1.,  2.,  2.,  2.,  1.,
        2.,  2.,  2.,  1.,  2.,  2.,  1.,  2.,  2.,  1.,  2.,  1.,  1.,
        1.,  1.,  1.,  2.,  2.,  1.,  2.,  2.,  1.])

In [40]:
petalwidth = np.array(petal_width,dtype = "float16")
petalwidth

array([  0.,   0.,   0.,  10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,  10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0., 110.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,  16.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1., 111.,
         1.,   2.,   1.,   2.,   1.,   2.,   2.,   1.,   1.,   1.,   2.,
         2.,   1.,   2.,   2.,   2.,   2.,   1.,   2.,   2.,   1.,   2.,
         2.,   2.,   1.,   2.,   1.,   1.,   1.,   2.,   1.,   1.,   2.,
         2.,   1.,   1.,   2.,   2.,   1.,   1.,   2.,   2.,   2.,   1.,
         2.,   2.,   2.,   1.,   2.,   2.,   1.,   

## 2.what is the mean value of sepal length


In [41]:
sepallength = np.mean(sepal_length)  # mean
sepallength

5.242424242424242

## 3.sort the sepal width in ascending order


In [42]:
sepalwidth = np.sort(sepal_width) #sort
sepalwidth

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 4., 4., 4., 4.], dtype=float16)

## 4.apply all statistical measures on sepal with and length


### sepal width


In [43]:
np.mean(sepal_width) # mean


2.63

In [44]:
np.median(sepal_width) # median


3.0

In [45]:
np.var(sepal_width) #variance


0.2815

In [46]:
np.std(sepal_width) #standard deviation


0.531

In [47]:
Range = np.max(sepal_width)-np.min(sepal_width) # range
Range

2.0

In [48]:
Q3 = np.percentile(sepal_width,75)  #IQR
Q1 = np.percentile(sepal_width,25)
IQR = Q3 - Q1
IQR

1.0

## sepal length


In [49]:
np.mean(sepal_length)  # mean


5.242424242424242

In [50]:
np.median(sepal_length) #median


5.0

In [51]:
np.var(sepal_length) # variance


1.6624426078971535

In [52]:
np.std(sepal_length) #standard deviation


1.2893574399277934

In [53]:
Range = np.max(sepal_length) - np.min(sepal_length) # range
Range

8.0

## 5.after cleaning the data save the file as "cleaned_Iris.txt" and load to jupter again

In [55]:
sepal = np.hstack((sepal_length,sepal_width))
sepal

array([ 5.,  4.,  4.,  4.,  5.,  5.,  4.,  5.,  4.,  4.,  5.,  4.,  4.,
        4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  4.,  5.,  4.,  5.,
        5.,  5.,  5.,  4.,  4.,  5.,  5.,  5.,  4.,  5.,  5.,  4.,  4.,
        5.,  5.,  4.,  4.,  5.,  5.,  4.,  5.,  4.,  5.,  5.,  7.,  6.,
        6.,  5.,  6.,  5.,  5.,  4.,  6.,  5.,  5.,  5.,  6.,  6.,  5.,
        6.,  5.,  5.,  6.,  5.,  5.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  5.,  5.,  5.,  5.,  6.,  5.,  6.,  6.,  6.,  5.,  5.,  5.,
        6.,  5.,  5.,  5.,  5.,  5.,  6.,  5.,  5.,  6.,  5.,  7.,  6.,
        6.,  7.,  4.,  7.,  6.,  7.,  6.,  6.,  6.,  5.,  5.,  6.,  6.,
        7.,  7.,  6.,  6.,  5.,  7.,  6.,  6.,  7.,  6.,  6.,  6.,  5.,
       -1., -1.,  6.,  6.,  6.,  7.,  6.,  6.,  6.,  6.,  6.,  6.,  5.,
        6.,  6.,  6.,  6.,  6.,  6.,  5.,  5.,  7., -1., -1.,  7.,  4.,
        7.,  6.,  5.,  5.,  7.,  6.,  7.,  6.,  6.,  3.,  3.,  3.,  3.,
        3.,  3.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,  4.,  4

In [56]:
petal = np.hstack((petal_length,petal_width))
petal

array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   4.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   4.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   4.,   4.,   4.,   4.,   4.,
         4.,   4.,   3.,   4.,   3.,   3.,   4.,   4.,   4.,   3.,   4.,
         4.,   4.,   4.,   3.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,
         5.,   4.,   3.,   4.,   3.,   3.,   5.,   4.,   4.,   4.,   4.,
         4.,   4.,   4.,   4.,   4.,   3.,   4.,   4.,   4.,   4.,   3.,
         4.,   6.,   5.,   5.,   5.,   5.,   6.,   4.,   6.,   5.,   6.,
         5.,   5.,   4.,   5.,   5.,   5.,   5.,   6.,   6.,   5.,   5.,
         4.,   6.,   4.,   5.,   6.,   4.,   4.,   5.,   5.,   6.,   4.,
         5.,   5.,   5.,   6.,   5.,   5.,   4.,   5.,   4.,   5.,   5.,
         5.,   5.,   4.,   5.,   5.,   5.,   5.,   

In [57]:
iris = np.hstack((sepal,petal))
iris

array([  5.,   4.,   4.,   4.,   5.,   5.,   4.,   5.,   4.,   4.,   5.,
         4.,   4.,   4.,   5.,   5.,   5.,   5.,   5.,   5.,   5.,   5.,
         4.,   5.,   4.,   5.,   5.,   5.,   5.,   4.,   4.,   5.,   5.,
         5.,   4.,   5.,   5.,   4.,   4.,   5.,   5.,   4.,   4.,   5.,
         5.,   4.,   5.,   4.,   5.,   5.,   7.,   6.,   6.,   5.,   6.,
         5.,   5.,   4.,   6.,   5.,   5.,   5.,   6.,   6.,   5.,   6.,
         5.,   5.,   6.,   5.,   5.,   6.,   6.,   6.,   6.,   6.,   6.,
         6.,   6.,   5.,   5.,   5.,   5.,   6.,   5.,   6.,   6.,   6.,
         5.,   5.,   5.,   6.,   5.,   5.,   5.,   5.,   5.,   6.,   5.,
         5.,   6.,   5.,   7.,   6.,   6.,   7.,   4.,   7.,   6.,   7.,
         6.,   6.,   6.,   5.,   5.,   6.,   6.,   7.,   7.,   6.,   6.,
         5.,   7.,   6.,   6.,   7.,   6.,   6.,   6.,   5.,  -1.,  -1.,
         6.,   6.,   6.,   7.,   6.,   6.,   6.,   6.,   6.,   6.,   5.,
         6.,   6.,   6.,   6.,   6.,   6.,   5.,   

In [58]:
np.savetxt('cleaned_iris.txt',iris)

In [59]:
np.loadtxt('cleaned_iris.txt')


array([  5.,   4.,   4.,   4.,   5.,   5.,   4.,   5.,   4.,   4.,   5.,
         4.,   4.,   4.,   5.,   5.,   5.,   5.,   5.,   5.,   5.,   5.,
         4.,   5.,   4.,   5.,   5.,   5.,   5.,   4.,   4.,   5.,   5.,
         5.,   4.,   5.,   5.,   4.,   4.,   5.,   5.,   4.,   4.,   5.,
         5.,   4.,   5.,   4.,   5.,   5.,   7.,   6.,   6.,   5.,   6.,
         5.,   5.,   4.,   6.,   5.,   5.,   5.,   6.,   6.,   5.,   6.,
         5.,   5.,   6.,   5.,   5.,   6.,   6.,   6.,   6.,   6.,   6.,
         6.,   6.,   5.,   5.,   5.,   5.,   6.,   5.,   6.,   6.,   6.,
         5.,   5.,   5.,   6.,   5.,   5.,   5.,   5.,   5.,   6.,   5.,
         5.,   6.,   5.,   7.,   6.,   6.,   7.,   4.,   7.,   6.,   7.,
         6.,   6.,   6.,   5.,   5.,   6.,   6.,   7.,   7.,   6.,   6.,
         5.,   7.,   6.,   6.,   7.,   6.,   6.,   6.,   5.,  -1.,  -1.,
         6.,   6.,   6.,   7.,   6.,   6.,   6.,   6.,   6.,   6.,   5.,
         6.,   6.,   6.,   6.,   6.,   6.,   5.,   